permalink: pretty
baseurl: '/potter-jeopardy'
url: ''

title: Potter Jeopardy

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

include:
  - _static

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
